#!/usr/bin/env python3
"""R06 checker: exit 1 if SKILLS-INDEX.md is missing or not machine-generated.
A generated index carries the auditor's provenance line. Usage: index_is_generated.py <index.md>"""
import os, sys

MARKER = "Generated by"

def main():
    if len(sys.argv) < 2:
        print("usage: index_is_generated.py <index.md>"); return 2
    p = os.path.expanduser(sys.argv[1])
    if not os.path.isfile(p):
        print("  missing index: %s" % p); return 1
    head = open(p, encoding="utf-8", errors="replace").read(600)
    if MARKER not in head:
        print("  index lacks generated-provenance marker (%r) -> looks hand-curated" % MARKER); return 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
