#!/usr/bin/env python3
"""Regenerate the short docs/commands/**/*.md reference stubs from each command's own source.

A stub page is either one this script wrote (it carries MARKER) or a legacy 23-line stub from
#172 (a `[mode]` synopsis + "Browse all commands" footer, <= 30 lines). Hand-written pages are
never touched. The command file is found by path: docs/commands/<a>/<b>.md -> commands/<a>/<b>.md.

What goes on the page, in order of preference — nothing is guessed:
  1. frontmatter `arguments:` -> an Arguments table (name / required / default / description)
  2. else, usage examples from the command body's code blocks (lines starting with the command
     or its short alias, e.g. `/docs-check`, which is rewritten to the full `/craft:...` name)
  3. else, "No declared arguments" + a pointer to the source

Frontmatter arguments carry no flag-vs-positional field, so the synopsis never renders them as
`--flags`; the table is the authority.

Usage:
  gen-command-stub-docs.py           rewrite stale stub pages
  gen-command-stub-docs.py --check   exit 1 if any stub page is out of date (CI mode)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "commands"
CMDS = ROOT / "commands"
MARKER = "<!-- generated by scripts/gen-command-stub-docs.py from {src} — edit the command's frontmatter, not this page -->"
MAX_EXAMPLES = 4


def frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    return (m.group(1), text[m.end():]) if m else ("", text)


def fm_scalar(fm, key):
    m = re.search(rf"^{key}:\s*(.+)$", fm, re.MULTILINE)
    return m.group(1).strip().strip('"').strip("'") if m else None


def fm_arguments(fm):
    """Parse the `arguments:` list (name/description/required/default) without a YAML dep."""
    m = re.search(r"^arguments:\s*\n((?:[ \t]+.*\n?)+)", fm + "\n", re.MULTILINE)
    if not m:
        return []
    args, cur = [], None
    for line in m.group(1).splitlines():
        item = re.match(r"^\s*-\s+name:\s*(.+)$", line)
        if item:
            cur = {"name": item.group(1).strip().strip('"')}
            args.append(cur)
            continue
        kv = re.match(r"^\s+(description|required|default|type):\s*(.*)$", line)
        if kv and cur is not None:
            cur[kv.group(1)] = kv.group(2).strip().strip('"').strip("'")
    return args


def usage_examples(body, name):
    short = "/" + name.split(":")[-1]
    out, in_block = [], False
    for line in body.splitlines():
        if line.startswith("```"):
            in_block = not in_block
            continue
        s = line.strip()
        if in_block and (s == name or s.startswith(name + " ") or s == short or s.startswith(short + " ")):
            if s == short or s.startswith(short + " "):
                s = name + s[len(short):]  # show the real namespaced command, never a bare alias
            if s not in out:
                out.append(s)
            if len(out) == MAX_EXAMPLES:
                break
    return out


def cell(s):
    return (s or "").replace("|", "\\|")


def render(doc_rel, cmd_path):
    fm, body = frontmatter(cmd_path.read_text(encoding="utf-8"))
    name = "/craft:" + str(cmd_path.relative_to(CMDS).with_suffix("")).replace("/", ":")
    desc = fm_scalar(fm, "description") or name
    src = f"commands/{cmd_path.relative_to(CMDS)}"
    args = fm_arguments(fm)
    depth = len(Path(doc_rel).parts) - 1
    hub = "../" * depth + "hub.md"
    lines = [MARKER.format(src=src), "", f"# {name}", "", f"> **{desc}**", "", "---", "", "## Synopsis", "", "```bash"]
    examples = [] if args else usage_examples(body, name)
    lines += [f"{name} [arguments]"] if args else (examples or [name])
    lines += ["```", ""]
    if args:
        lines += ["## Arguments", "", "| Argument | Required | Default | Description |", "|---|---|---|---|"]
        for a in args:
            req = "yes" if a.get("required", "false").lower() == "true" else "no"
            lines.append(f"| `{cell(a['name'])}` | {req} | {cell(a.get('default', '—')) or '—'} | {cell(a.get('description', ''))} |")
        lines.append("")
    elif not examples:
        lines += ["No declared arguments and no usage examples in the command file — see its source.", ""]
    lines += ["---", "", "## See Also", "", f"- [/craft:hub]({hub}) — Browse all commands",
              f"- Source: `{src}`", ""]
    return "\n".join(lines)


def is_stub(text):
    if text.startswith("<!-- generated by scripts/gen-command-stub-docs.py"):
        return True
    return (len(text.splitlines()) <= 30 and "Browse all commands" in text
            and re.search(r"^/craft:\S+ \[mode\]$", text, re.MULTILINE) is not None)


def main():
    check = "--check" in sys.argv
    stale, missing_src = [], []
    for doc in sorted(DOCS.rglob("*.md")):
        text = doc.read_text(encoding="utf-8")
        if not is_stub(text):
            continue
        rel = doc.relative_to(DOCS)
        cmd = CMDS / rel
        if not cmd.exists():
            missing_src.append(str(rel))
            continue
        new = render(str(rel), cmd)
        if new != text:
            stale.append(str(rel))
            if not check:
                doc.write_text(new, encoding="utf-8")
    for r in missing_src:
        print(f"WARN  stub docs/commands/{r} has no command file commands/{r}", file=sys.stderr)
    verb = "out of date" if check else "regenerated"
    for r in stale:
        print(f"{verb}: docs/commands/{r}")
    if check and stale:
        print(f"\n{len(stale)} stub page(s) out of date — run scripts/gen-command-stub-docs.py", file=sys.stderr)
        return 1
    if not stale:
        print("all stub pages current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
